UiPath/uipath-python

pyproject.toml, src/uipath/_folder_context.py, src/uipath/_services/actions_service.py, src/uipath/_services/context_grounding_service.py, src/uipath/models/interrupt_models.py, uv.lock
- add support for folder path in action service
=> feat: add support for folder path in action service

pyproject.toml, src/uipath/_cli/_runtime/_contracts.py, src/uipath/models/__init__.py, uv.lock
- add folder info properties in resume trigger contract
- made interrupt models serializable
❗should be merged after https://github.com/UiPath/uipath-python/pull/266
=> feat: add folder info in resume trigger contract

.vscode/settings.json, pyproject.toml, src/uipath/tracing/__init__.py, src/uipath/tracing/_otel_exporters.py, src/uipath/tracing/_traced.py, src/uipath/tracing/_utils.py, tests/tracing/test_span_utils.py, tests/tracing/test_traced.py, uv.lock
I incorporated an LlmOpsHttpExporter that's compatible with OpenTelemetry, and a @traced() attribute that uses OpenTelemetry. Also, I've added a TracedDecoratorRegistry that I'll use in UiPath-langchain to replace the Langchain tracer instead of OpenTelemetry. Consequently, all @traced() methods will behave differently.
Add open telemetry tracing
Example
```python
from time import sleep
from opentelemetry import trace
import os
from aio_tracer import traced, wait_for_tracer
import asyncio
tracer = trace.get_tracer(__name__)
@traced()
def print_env_vars():
for key, value in os.environ.items():
print(f"{key}={value}")
@traced()
def sync_function(x, y):
sleep(1)
return x + y
@traced()
async def async_function(x, y):
await asyncio.sleep(1)
return x * y
@traced()
def generator_function(n):
for …
```
=> feat(trace): add otel tracing

pyproject.toml, src/uipath/_services/actions_service.py, uv.lock
- when creating an action, we need to fetch from apps the `appId` given the `appName`
- apps API may return multiple app schemas from different folders current user (or robot) has access to
- if `app_folder_path` is provided -> use it to match the folder FQN
Note ❗ This should be a temporary fix until apps adds folder filtering support on `deployed-action-apps-schemas` API
[Apps ticket](https://uipath.atlassian.net/jira/software/c/projects/APPS/issues/APPS-28791?filter=reportedbyme&jql=project%20%3D%20%22APPS%22%20AND%20reporter%20IN%20%28currentUser%28%29%29%20ORDER%20BY%20created%20DESC)
=> feat: filter app schema by FQN

pyproject.toml, src/uipath/_cli/cli_pack.py, uv.lock
Configurable files & file extensions inclusion lists for `uipath pack`:
`uipath.json`:
```json
{
"settings":{
"filesIncluded": [
"github-mcp-server"
],
"fileExtensionsIncluded": [
"go"
]
}
}
```
=> feat: add packed files settings to uipath.json

pyproject.toml, src/uipath/_cli/_utils/_processes.py, src/uipath/_cli/cli_auth.py, src/uipath/_cli/cli_invoke.py, src/uipath/_cli/cli_publish.py, uv.lock
- add --force flag for auth
- retrieve process details by package name and version (in case it gets renamed in pw)
=> CLI improvements

docs/core/attachments.md, src/uipath/_services/__init__.py, src/uipath/_services/attachments_service.py, src/uipath/_services/jobs_service.py, src/uipath/_uipath.py, src/uipath/models/__init__.py, src/uipath/models/attachment.py, tests/sdk/services/test_attachments_service.py, tests/sdk/services/test_jobs_service.py
These endpoints were tensted and work fine. 
```
[2025-05-12 18:38:12,677][INFO] Attachment uploaded, key: 28f884a3-9cab-4ccd-c85f-08dd9164ced1
[2025-05-12 18:38:13,324][INFO] Downloaded attachment: ticket-classification-attachment_2
[2025-05-12 18:38:13,662][INFO] Attachments after upload: [Attachment(name='ticket-classification-attachment_2', organization_unit_id=1, tenant_id=1, creation_time=datetime.datetime(2025, 5, 12, 15, 38, 12, 530000, tzinfo=TzInfo(UTC)), last_modification_time=None, key=UUID('28f884a3-9cab-4ccd-c85f-08dd9164ced1'), LastModifierUserId=None, CreatorUserId=3405220, BlobFileAccess=None)]
[2025-05-12 18:38:14,491][INFO] Delete attachment result: None
[2025-05-12 18:38:14,835][INFO] Attachments after deletion: []
[2025-05-12 18:38:14,836][INFO] Attachment operations …
```
=> Attachments: support endpoints in sdk

pyproject.toml, src/uipath/_cli/_auth/_auth_server.py, src/uipath/_cli/_auth/auth_config.json, src/uipath/_cli/cli_auth.py
- https://github.com/UiPath/first-party-service-metadata/pull/2199
```toml
[project]
"uipath-nightly==2.0.55.dev1003760342",
"uipath-nightly>=2.0.55.dev1003760000,<2.0.55.dev1003770000"
]
```
=> cli: use http instead of https for cli auth

pyproject.toml, src/uipath/_utils/_url.py
The previous implementation would not take query string params into consideration:
```python
def _is_relative_url(self, url: str) -> bool:
parsed = urlparse(url)
print(f"url: {url}")
print(f"parsed: {parsed}")
return parsed.hostname is None and parsed.path == url
```
```cmd
[2025-05-18 09:00:59,576][INFO] url: mcp/mcp/gmaps-hosted/runtime/abort?runtimeId=c370591f-a68e-4103-9e4b-d02341fa6a35
[2025-05-18 09:00:59,576][INFO] parsed: ParseResult(scheme='', netloc='', path='mcp_/mcp/gmaps-hosted/runtime/abort', params='', query='runtimeId=c370591f-a68e-4103-9e4b-d02341fa6a35', fragment='')
[2025-05-18 09:00:59,576][INFO] self._is_relative_url(url): self._is_relative_url(url)=False
```
=> fix: proper relative url parsing

docs/core/traced.md
`traced` is not correctly documented
=> feat(docs): fix tracing imports

pyproject.toml, src/uipath/_services/jobs_service.py, uv.lock
- add folder support for job retrieve
=> feat: add folder support for job retrieve

.github/workflows/publish-dev.yml, pyproject.toml
move nightly to testpy
see results here https://test.pypi.org/project/uipath/#history
```toml
[project]
"uipath==2.0.62.dev1003970405",
"uipath>=2.0.62.dev1003970000,<2.0.62.dev1003980000"
]
```
=> feat(build): move nightly to testpy

pyproject.toml, src/uipath/tracing/_traced.py
- Lazy load tracer for traced
- add `register_current_span_provider` for custom trace context
```toml
[project]
"uipath==2.0.64.dev1004020435",
"uipath>=2.0.64.dev1004020000,<2.0.64.dev1004030000"
]
```
=> fix(tracer): lazy load tracer for traced

.vscode/launch.json, docs/cli/index.md, pyproject.toml, src/uipath/_cli/_utils/_debug.py, src/uipath/_cli/cli_run.py, uv.lock
For step-by-step debugging with breakpoints and variable inspection (supported from `2.0.66` onward):
```console
[uv] pip install debugpy
uipath run [ENTRYPOINT] [INPUT] --debug
```
For vscode: add the [debug configuration](https://github.com/UiPath/uipath-python/blob/main/.vscode/launch.json) in your .vscode/launch.json file.
Place breakpoints in your code where needed.
Use the shortcut `F5`, or navigate to Run -> Start Debugging -> Python Debugger: Attach
Upon starting the debugging process, one should see the following logs in terminal:
```console
🐛 Debug server started on port 5678
📌 Waiting for debugger to attach...
- VS Code: Run -> Start Debugging -> Python Debugger: Attach
✓  Debugger attached successfully!
```
- ❌ add pycharm support `pydevd-pycharm` (delayed scope)
=> feat: add debug flag on run

pyproject.toml, src/uipath/_services/context_grounding_service.py, src/uipath/_services/folder_service.py, tests/sdk/services/test_context_grounding_service.py, tests/sdk/services/test_folder_service.py, uv.lock
- use `odata/Folders` api instead of `FoldersNavigation` to compare exact equality between folder names
- update tests to use new api
```toml
[project]
"uipath==2.0.67.dev1004070452",
"uipath>=2.0.67.dev1004070000,<2.0.67.dev1004080000"
]
```
=> fix: use odata api for folder search

pyproject.toml, src/uipath/_services/folder_service.py, tests/sdk/services/test_context_grounding_service.py, tests/sdk/services/test_folder_service.py, uv.lock
this PR rollbacks the changes added here:
https://github.com/UiPath/uipath-python/pull/407
- take 20 folders at a time
- pagination support on client side
The current implementation is subject to change, after new API is added in Orchestrator.
```toml
[project]
"uipath==2.0.68.dev1004080453",
"uipath>=2.0.68.dev1004080000,<2.0.68.dev1004090000"
]
```
=> fix: rollback to FoldersNavigation usage

pyproject.toml, src/uipath/_services/context_grounding_service.py
Added optional parameter to control data ingestion after files are uploaded to context grounding indexes.
=> chore: context grounding, optional index ingestion

pyproject.toml, src/uipath/_cli/cli_pack.py
Include the `uv.lock` file inside the `.nupkg` for faster dependencies resolve
```toml
[project]
"uipath==2.0.72.dev1004140485",
"uipath>=2.0.72.dev1004140000,<2.0.72.dev1004150000"
]
```
=> feat: pack uv.lock

pyproject.toml, src/uipath/_cli/cli_pack.py, tests/cli/test_pack.py, uv.lock
Adds support for parsing and saving project dependencies from `pyproject.toml` into the package’s `operate.json`.
```toml
[project]
"uipath==2.0.76.dev1004270554",
"uipath>=2.0.76.dev1004270000,<2.0.76.dev1004280000"
]
```
=> feat: save dependencies metadata

pyproject.toml, src/uipath/_cli/_utils/_constants.py, src/uipath/_cli/cli_pack.py
This PR centralizes binary file extension logic, updates the pack command to use the new utility, and bumps the package version.
- Added `is_binary_file` and grouped binary extensions in a constants module.
- Refactored `cli_pack.pack_fn` to replace its inline `binary_extensions` list with `is_binary_file`.
- Incremented project version to `2.0.77`.
In some near future, we probably need to read all files in binary mode by default and have a special treatment for new line sensitive files, eg:
```python
line_ending_sensitive_files = {'.json', '.xml', '.yaml', '.yml', '.toml'}
```
=> fix: add binary file extensions to prevent corruption during pack

pyproject.toml, src/uipath/_cli/middlewares.py
Surface exception and call stack when middleware fails to load. 
This exception happens when you try to use the latest `uipath-langchain` extension which is no longer compatible with `langgraph` version < 0.5.0.
=> fix: console log middleware loading exceptions

docs/core/getting_started.md
This PR adds documentation warning users about the need to properly escape JSON input when using the `uipath run` command across different shell environments.
=> docs: warning for input escaping

pyproject.toml, src/uipath/_cli/__init__.py, src/uipath/_cli/_utils/_common.py, src/uipath/_cli/_utils/_studio_project.py, src/uipath/_cli/cli_pack.py, src/uipath/_cli/cli_pull.py, src/uipath/_cli/cli_push.py, tests/cli/test_pull.py, tests/cli/test_push.py, tests/cli/utils/common.py, uv.lock
This PR introduces a new `pull` command to the UiPath CLI, enabling pulling remote project files from a Studio Web solution to the local environment. This complements the existing `push` command to provide full bidirectional sync capabilities.
- Added `uipath pull` command
- Automatically syncs remote files to local project
- Handles file downloads and updates
- Maintains project structure integrity
- Downloads new files that don't exist locally
- Updates existing files with remote changes (with user confirmation)
- Preserves local files that match remote content
- Handles JSON formatting and line ending normalization
- Supports special folders like `evals` with subfolders:
- `eval-sets`: Evaluation set configurations
- `evaluators`: Evaluator definitions
- Recursively processes remote …
=> feat: CLI add pull command

pyproject.toml, src/uipath/_cli/_evals/_evaluators/_evaluator_factory.py, src/uipath/_cli/_evals/_models/_evaluation_set.py, src/uipath/_cli/_evals/evaluation_service.py, src/uipath/_cli/cli_eval.py, src/uipath/_cli/cli_invoke.py, uv.lock
Added support for running specific evaluations within an evaluation set through a new `--eval-ids` flag. This enhancement allows users to selectively execute individual evaluations rather than running the entire evaluation set, providing better granular control and aligning with current StudioWeb behavior.
```bash
uipath eval [entrypoint] [evaluationSet] [--eval-ids EVAL_IDS]
```
**Run all evaluations (default behavior):**
```bash
uipath eval
uipath eval agent .\evals\eval-sets\evaluation_set.json
```
**Run specific evaluations by ID:**
```bash
uipath eval --eval-ids '["00000000-0000-0000-0000-000000000000", "00000000-0000-0000-0000-000000000001"]'
uipath eval agent .\evals\eval-sets\evaluation_set.json --eval-ids '["00000000-0000-0000-0000-000000000000", …
```
=> Run specific evaluations

pyproject.toml, src/uipath/tracing/_utils.py
Add back folder key in trace id 
```toml
[project]
"uipath==2.1.23.dev1004360786",
"uipath>=2.1.23.dev1004360000,<2.1.23.dev1004370000"
]
```
=> fix(trace): add back folder keys in traces

src/uipath/_cli/_runtime/_contracts.py, src/uipath/_cli/_runtime/_logging.py
This PR introduces the ability to inject a custom log handler into the UiPath runtime logging system instead of relying solely on the default file or stdout handlers.
- Added configurable `log_handler` parameter to both `LogsInterceptor` and `UiPathRuntimeContext`
- Modified the logging initialization logic to use the provided handler when available
- Updated type annotations to accommodate the new handler type
```python
class RunContextLogHandler(logging.Handler):
"""Custom log handler that sends logs to CLI UI."""
def __init__(
self,
run_id: str,
on_log: Callable[[LogMessage], None],
):
super().__init__()
self.run_id = run_id
self.on_log = on_log
def emit(self, record: logging.LogRecord):
"""Emit a log record to CLI UI."""
try:
log_msg = LogMessage(
run_id=self.run_id, …
```
=> fix: configurable log handler

src/uipath/_cli/__init__.py, src/uipath/_cli/cli_dev.py, src/uipath/_cli/middlewares.py
This PR adds a new `dev` command to the UiPath CLI that launches an interactive debugging interface. The implementation follows the existing CLI command pattern and integrates with the middleware system.
- Introduces a new `dev` CLI command with an interface parameter (defaults to "terminal")
- Integrates the command with the existing middleware system for extensibility
=> feat: add dev command

src/uipath/_cli/_dev/_terminal/_components/_history.py, src/uipath/_cli/_dev/_terminal/_models/_execution.py
This PR fixes real-time updates for terminal run duration display. The changes ensure that running executions show updated duration times without requiring manual refresh, improving user experience by providing live feedback on execution progress.
- Increased duration string display width from 4 to 6 characters to accommodate longer duration formats
- Added automatic refresh mechanism that updates running items every 5 seconds
=> fix: update terminal run duration realtime

src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_details.py, src/uipath/_cli/_dev/_terminal/_models/_messages.py
This PR fixes traceback display in terminal error logs by enhancing the logging system to support rich traceback rendering instead of simple error messages.
- Modified `LogMessage` to accept both strings and `Rich` renderables for enhanced error display
- Updated error logging to generate `Rich` `Traceback` objects with detailed stack traces and local variables
- Enhanced log display logic to handle both string messages and `Rich` renderables appropriately
```toml
[project]
"uipath==2.1.36.dev1005470941",
"uipath>=2.1.36.dev1005470000,<2.1.36.dev1005480000"
] …
```
=> fix: traceback in terminal error logs

src/uipath/_cli/_runtime/_contracts.py, src/uipath/agent/conversation/__init__.py, src/uipath/agent/conversation/async_stream.py, src/uipath/agent/conversation/citation.py, src/uipath/agent/conversation/content.py, src/uipath/agent/conversation/conversation.py, src/uipath/agent/conversation/event.py, src/uipath/agent/conversation/exchange.py, src/uipath/agent/conversation/message.py, src/uipath/agent/conversation/meta.py, src/uipath/agent/conversation/tool.py
This PR adds Pydantic models that define a comprehensive JSON event schema for conversations between a client (UI) and an LLM/agent. The implementation establishes a hierarchical conversation structure supporting real-time streaming events, tool calls, citations, and async input streams.
- Introduces conversation event models with proper field aliasing and validation
- Implements a structured hierarchy: Conversation → Exchange → Message → Content Parts/Tool Calls
- Adds conversation handler integration to the runtime context
=> feat: add conversational agent contracts

src/uipath/_services/processes_service.py
Fix: https://github.com/UiPath/uipath-python/issues/539
```toml
[project]
"uipath==2.1.44.dev1005591056",
"uipath>=2.1.44.dev1005590000,<2.1.44.dev1005600000"
]
```
=> fix(job_key): changed job_id to job_key

pyproject.toml, src/uipath/_cli/_utils/_studio_project.py, src/uipath/_services/_base_service.py, src/uipath/_services/actions_service.py, src/uipath/_services/api_client.py, src/uipath/_services/assets_service.py, src/uipath/_services/processes_service.py, tests/sdk/services/test_base_service.py, tests/sdk/services/test_processes_service.py
Fix: https://github.com/UiPath/uipath-python/issues/508
```toml
[project]
"uipath==2.1.48.dev1005631078",
"uipath>=2.1.48.dev1005630000,<2.1.48.dev1005640000"
]
```
=> fix(httpx_header): allow httpx determine the correct header

pyproject.toml, src/uipath/_cli/_runtime/_contracts.py
This change updates the `with_defaults` classmethod in `UiPathRuntimeContext` to safely apply keyword arguments (`kwargs`) when constructing the context.
Key changes:
- Previously, `setattr(base, k, v)` would fail if `k` was not a defined attribute on the `Pydantic` model.
- Now, the method supports `extra="allow"` in the model config, so any extra fields in `kwargs` are applied without raising `AttributeError`.
- Maintains full support for overriding existing fields while allowing flexible runtime extensions.
=> fix: runtime context set kwargs attributes

pyproject.toml, src/uipath/_cli/_runtime/_contracts.py
```toml
[project]
"uipath==2.1.54.dev1005941137",
"uipath>=2.1.54.dev1005940000,<2.1.54.dev1005950000"
]
```
=> fix: allow extra runtime context

pyproject.toml, src/uipath/tracing/_traced.py
Fix traced parent span id.
```toml
[project]
"uipath==2.1.55.dev1005961178",
"uipath>=2.1.55.dev1005960000,<2.1.55.dev1005970000"
]
```
=> fix(traced): fix parent for traced

.github/workflows/test.yml
Currently hardcoded to contents of `.python-version` file, instead of using what is defined in the strategy matrix
=> chore(ci): use different python versions for tests

pyproject.toml, src/uipath/_cli/_push/sw_file_handler.py, src/uipath/_cli/_utils/_studio_project.py
The id of the project folder may `None` for root folders. Addressing this bug introduced in [this PR](https://github.com/UiPath/uipath-python/commit/bc4bf7f4daf668ca5d582b06bd53061e98099252).
=> fix(ProjectStructure): project structure id representation

pyproject.toml, src/uipath/_cli/_runtime/_contracts.py, src/uipath/_cli/_runtime/_logging.py
When multiple runtimes execute in parallel, logs from different executions get mixed together because they all share the same global logging handlers. This makes it impossible to track which logs belong to which execution.
**Root cause:** `LogsInterceptor` modifies global logging state, causing all parallel executions to interfere with each other.
Use `contextvars.ContextVar` to scope logs per execution without fighting global state:
- Context variable for execution tracking - `current_execution_id` is set per async context and automatically propagates through async calls
- Execution-aware filter - `ExecutionContextFilter` checks the context variable to route logs to the correct handler
- Additive handlers in parallel mode - When `execution_id` is provided, handlers are added instead of …
=> fix: isolate logging across concurrent runtime executions

pyproject.toml, src/uipath/_cli/_runtime/_logging.py
```python
class ExecutionLogHandler(logging.Handler):
"""Custom log handler that stores execution logs."""
def __init__(
self,
execution_id: str,
):
super().__init__()
self.execution_id = execution_id
def emit(self, record: logging.LogRecord):
"""Store execution log"""
try:
log_msg = {
"execution_id": self.execution_id,
"level": record.levelname,
"message": self.format(record),
}
print(f"[ExecutionLogHandler] {log_msg}", file=sys.__stderr__)
except Exception as e:
print(f"[ExecutionLogHandler ERROR] {e}", file=sys.__stderr__)
pass
...
runtime_context: C = self.factory.new_context(
execution_id=eval_item.id,
input_json=eval_item.inputs,
log_handler=ExecutionLogHandler(
execution_id=eval_item.id,
),
)
```
```toml
[project] …
```
=> fix: intercept children execution logs
