UiPath/uipath-python

.github/workflows/ci.yml, .github/workflows/commitlint.yml, pyproject.toml, src/uipath/models/interrupt_models.py
- add folder info to interrupt models
- add commit-lint instructions
=> feat: add folder info to interrupt models

pyproject.toml, src/uipath/_cli/_auth/auth_config.json
- add RCS.FolderAuthorization scope
=> feat: add RCS.FolderAuthorization scope

.github/workflows/ci.yml, pyproject.toml, uv.lock
- stop running commit-lint on merge commits
=> ci: stop running commit-lint on merge commits

pyproject.toml, src/uipath/_cli/cli_init.py, src/uipath/_cli/cli_pack.py, uv.lock
- package yaml files 
- use posix file separator
=> feat: package yaml files + use unix file separator

pyproject.toml, src/uipath/tracing/_otel_exporters.py, tests/tracing/test_otel_exporters.py
Add retry logic on trace exporter, also add tests for exporter.
=> feat(tracer): add retry on trace export

pyproject.toml, src/uipath/tracing/__init__.py, src/uipath/tracing/_traced.py, tests/tracing/test_tracing_manager.py
Add a better way to overwrite `@traced()` attribute. In this way we keep track of every decorated `@traced()` method and we allow devs to rewrite the implementation at runtime.
=> feat(trace): add support to replace traced implementation

mkdocs.yml
- https://github.com/UiPath/uipath-langchain-python/pull/44/files
=> feat(docs): update docs

pyproject.toml, src/uipath/_cli/__init__.py, src/uipath/_cli/_auth/_auth_server.py, src/uipath/_cli/_utils/_common.py, src/uipath/_cli/_utils/_folders.py, src/uipath/_cli/_utils/_processes.py, src/uipath/_cli/cli_auth.py, src/uipath/_cli/cli_init.py, src/uipath/_cli/cli_invoke.py, src/uipath/_cli/cli_new.py, src/uipath/_cli/cli_pack.py, src/uipath/_cli/cli_publish.py, src/uipath/_cli/spinner.py, uv.lock
- added CLI invoke command
- compose edit process link on PW publish
=> feat: CLI invoke

.github/workflows/publish-dev.yml, pyproject.toml, src/uipath/_cli/__init__.py
Add private builds for testing
=> feat(dev): add pr build

pyproject.toml, src/uipath/_cli/cli_invoke.py, src/uipath/_cli/cli_publish.py, uv.lock
- list available feeds on publish
=> feat: list available feeds on publish

pyproject.toml, src/uipath/_services/actions_service.py, src/uipath/_services/assets_service.py, src/uipath/_services/buckets_service.py, src/uipath/_services/connections_service.py, src/uipath/_services/context_grounding_service.py, src/uipath/_services/folder_service.py, src/uipath/_services/jobs_service.py, src/uipath/_services/llm_gateway_service.py, src/uipath/_services/processes_service.py, src/uipath/_services/queues_service.py, src/uipath/_utils/_user_agent.py, src/uipath/tracing/_traced.py
=> feat(trace): add trace

.github/workflows/publish-dev.yml
Update pr description instead of pr comment for devbuilds
```toml
[project]
"uipath-nightly==2.0.24.dev1002970058",
"uipath-nightly>=2.0.24.dev1002970000,<2.0.24.dev1002980000"
]
```
=> feat(dev): improve build pr dev message

pyproject.toml, src/uipath/tracing/_traced.py, tests/tracing/test_tracing_manager.py
```toml
[project]
"uipath-nightly==2.0.25.dev1002980060",
"uipath-nightly>=2.0.25.dev1002980000,<2.0.25.dev1002990000"
]
```
=> fix(tracer): fix problems for tracers with unkown parameters

pyproject.toml, src/uipath/_cli/_auth/_auth_server.py, src/uipath/_cli/_auth/_portal_service.py, src/uipath/_cli/_utils/_console.py, src/uipath/_cli/_utils/_folders.py, src/uipath/_cli/_utils/_processes.py, src/uipath/_cli/cli_auth.py, src/uipath/_cli/cli_deploy.py, src/uipath/_cli/cli_init.py, src/uipath/_cli/cli_invoke.py, src/uipath/_cli/cli_new.py, src/uipath/_cli/cli_pack.py, src/uipath/_cli/cli_publish.py, src/uipath/_cli/cli_run.py, tests/cli/test_init.py, uv.lock
```toml
[project]
"uipath-nightly==2.0.27.dev1003000073",
"uipath-nightly>=2.0.27.dev1003000000,<2.0.27.dev1003010000"
]
```
=> fix: cli consistent console logs

pyproject.toml, src/uipath/_cli/cli_init.py, uv.lock
-  log .env file creation as success
=> fix: log .env file creation as success

pyproject.toml, src/uipath/_cli/cli_init.py, src/uipath/_services/actions_service.py, uv.lock
- create action in same folder
- if no `app_folder_path` is provided, use the one set as env var
=> fix: create action in same folder

src/uipath/_cli/cli_init.py, src/uipath/_uipath.py, src/uipath/models/__init__.py, src/uipath/models/errors.py, tests/cli/test_init.py, tests/sdk/test_config.py
=> fix(cli): add new errors for missing data

pyproject.toml, src/uipath/_cli/cli_new.py, src/uipath/_cli/cli_run.py, uv.lock
- input file option
- log success message after debug run
```toml
[project]
"uipath-nightly==2.0.33.dev1003070120",
"uipath-nightly>=2.0.33.dev1003070000,<2.0.33.dev1003080000"
]
```
=> chore: add input file option

pyproject.toml, src/uipath/_cli/_utils/_processes.py, src/uipath/_cli/cli_init.py, src/uipath/_cli/cli_invoke.py, tests/cli/test_init.py, uv.lock
=> feat: empty env file

pyproject.toml, src/uipath/_cli/cli_invoke.py, src/uipath/models/__init__.py
- input file option for invoke command
=> feat: input file option for invoke command

pyproject.toml, src/uipath/_services/buckets_service.py, uv.lock
- pass positional args to retrieve methods
=> fix: pass positional args to retrieve methods

pyproject.toml, src/uipath/_services/context_grounding_service.py, src/uipath/models/context_grounding.py, uv.lock
- made response parameters optional
=> chore: made response parameters optional

pyproject.toml, src/uipath/_services/buckets_service.py, src/uipath/models/__init__.py, src/uipath/models/buckets.py, uv.lock
=> chore: add bucket model

.github/workflows/build.yml, .github/workflows/cd.yml
```toml
[project]
"uipath-nightly==2.0.46.dev1003490244",
"uipath-nightly>=2.0.46.dev1003490000,<2.0.46.dev1003500000"
]
```
=> chore(ci): update build and publish workflows to use pypa action

pyproject.toml, src/uipath/models/buckets.py, uv.lock
=> chore: PEP8 compliance

.github/workflows/build.yml, .github/workflows/cd.yml, pyproject.toml
This reverts commit 0d6d49e3c3771a032317413c18dadd51bead7395.
=> revert: update build and cd workflows for PyPI publishing

pyproject.toml, src/uipath/_services/buckets_service.py, uv.lock
=> chore: better error handling

pyproject.toml, src/uipath/_cli/_auth/_auth_server.py, src/uipath/_cli/cli_auth.py, src/uipath/_cli/cli_invoke.py, src/uipath/_cli/cli_run.py, src/uipath/_execution_context.py, src/uipath/_folder_context.py, src/uipath/_uipath.py, uv.lock
- `.env` precedence over sys env vars
=> feat: .env precedence over sys env vars

tests/cli/mocks/uipath-mock.json, tests/conftest.py
- add uipath.json mock
- renamed the mock file (was automatically excluded by .gitignore https://github.com/UiPath/uipath-python/blob/main/.gitignore#L15 )
=> fix: add uipath.json mock

docs/core/traced.md
Add documentation for our `@traced()` attribute
=> docs(traced): add traced documentation

src/uipath/_cli/cli_run.py, tests/cli/conftest.py, tests/cli/mocks/simple_script.py, tests/cli/mocks/uipath-simple-script-mock.json, tests/cli/test_invoke.py, tests/cli/test_publish.py, tests/cli/test_run.py, tests/conftest.py
=> chore: add tests for cli commands

pyproject.toml, src/uipath/tracing/_utils.py, tests/tracing/test_span_utils.py
map otel status error description to attributes error
```toml
[project]
"uipath-nightly==2.0.58.dev1003860361",
"uipath-nightly>=2.0.58.dev1003860000,<2.0.58.dev1003870000"
]
```
=> feat(tracing): otel status error description to attributes error

pyproject.toml, src/uipath/_cli/_utils/_constants.py, src/uipath/_cli/_utils/_parse_ast.py, src/uipath/_cli/cli_init.py, src/uipath/_services/assets_service.py, src/uipath/_services/buckets_service.py, src/uipath/_services/context_grounding_service.py, src/uipath/_services/processes_service.py, src/uipath/_utils/_infer_bindings.py, src/uipath/_utils/_read_overwrites.py, src/uipath/_utils/constants.py, tests/cli/mocks/bindings_script.py, tests/cli/test_init.py, tests/conftest.py, tests/sdk/test_bindings_inference.py, tests/sdk/test_overwrites.py, uv.lock
- infer bindings on missing methods
- refactor
- cli init tests
- read overwrites from expected folder
- overwrites read logic in decorator
```toml
[project]
"uipath-nightly==2.0.60.dev1003890381",
"uipath-nightly>=2.0.60.dev1003890000,<2.0.60.dev1003900000"
]
```
=> infer bindings

.github/workflows/publish-docs.yml, docs/index.md, mkdocs.yml, uv.lock
=> chore: include MCP docs

mkdocs.yml
=> chore: fix MCP docs

mkdocs.yml
=> fix docs section name

pyproject.toml, src/uipath/_cli/_auth/_auth_server.py, src/uipath/_cli/_auth/index.html, src/uipath/_cli/cli_auth.py, uv.lock
This PR implements proper handling of keyboard interrupts (Ctrl+C) during the CLI authentication flow. The changes convert the synchronous HTTP server to an asynchronous implementation and add a specific `KeyboardInterrupt` exception handler to provide a better user experience when authentication is cancelled.
- Converts the HTTP authentication server from synchronous to asynchronous using `asyncio`
- Adds proper `KeyboardInterrupt` handling with a user-friendly cancellation message
- Enhances the authentication HTML page with improved UI/UX including loading states, progress indicators, and error handling
```toml
[project]
"uipath==2.1.4.dev1004750656",
"uipath>=2.1.4.dev1004750000,<2.1.4.dev1004760000"
] …
```
=> fix: handle auth interrupt

pyproject.toml, src/uipath/_cli/_auth/auth_config.json
- request ProcessMining identity scope
- scope was already whitelisted for the sdk client
=> request ProcessMining identity scope

pyproject.toml, src/uipath/_services/connections_service.py, tests/sdk/services/test_connections_service.py
```toml
[project]
"uipath==2.1.11.dev1004900715",
"uipath>=2.1.11.dev1004900000,<2.1.11.dev1004910000"
]
```
=> fix(connections_service): rectified parameter name 

pyproject.toml, src/uipath/utils/_endpoints_manager.py
Add endpoints manager to fallback on orchestrator
```toml
[project]
"uipath==2.1.20.dev1005050782",
"uipath>=2.1.20.dev1005050000,<2.1.20.dev1005060000"
]
```
=> feat(llm): update endpoints manager

pyproject.toml, src/uipath/_services/_base_service.py, uv.lock
- `infer_content_type` was not working for sync requests client
=> fix: infer content type

src/uipath/_cli/_runtime/_runtime.py, src/uipath/_cli/cli_run.py
This PR decouples the runtime system from tracing functionality by extracting tracing setup from the runtime class and introducing a factory pattern for runtime creation with configurable tracing.
=> fix: decouple runtime from tracing

src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_details.py, src/uipath/_cli/_dev/_terminal/_models/_execution.py
This PR enhances error handling in the terminal interface by adding support for displaying structured error information using the `UiPathErrorContract` model.
=> fix: display error contract in terminal

src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_details.py, src/uipath/_cli/_dev/_terminal/_models/_execution.py, src/uipath/_cli/_runtime/_runtime.py
This PR fixes terminal input/output JSON handling by changing the runtime execution model to properly handle JSON data structures instead of raw strings. The changes ensure consistent JSON parsing and type handling throughout the execution pipeline.
=> fix: terminal input/output json

src/uipath/_cli/_dev/_terminal/_models/_execution.py
This PR fixes the terminal execution history status display by replacing plain text output with Rich-formatted text that includes colored status indicators and improved formatting.
- Replaces emoji status icons with text-based symbols for better terminal compatibility
- Adds color coding for different execution states (yellow for running, green for completed, red for failed)
- Implements fixed-width formatting for consistent column alignment in the terminal display
=> fix: terminal execution history status display

src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_history.py, src/uipath/_cli/_dev/_terminal/_components/_new.py, src/uipath/_cli/_dev/_terminal/_styles/terminal.tcss
=> fix: terminal style

pyproject.toml, src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_details.py, src/uipath/_cli/_dev/_terminal/_components/_resume.py, src/uipath/_cli/_dev/_terminal/_models/_execution.py, src/uipath/_cli/_dev/_terminal/_styles/terminal.tcss
This PR introduces handling for HITL scenarios in the dev terminal (suspend/resume)
=> fix: add terminal resume tab

src/uipath/_cli/_dev/_terminal/_models/_execution.py, src/uipath/_cli/_dev/_terminal/_styles/terminal.tcss, src/uipath/_cli/cli_dev.py
This PR adds debugging functionality to the development command by integrating `debugpy` support with configurable debug options.
=> fix: add debug parameters to dev command

pyproject.toml, src/uipath/_cli/_dev/_terminal/__init__.py, src/uipath/_cli/_dev/_terminal/_components/_chat.py, src/uipath/_cli/_dev/_terminal/_components/_details.py, src/uipath/_cli/_dev/_terminal/_styles/terminal.tcss, src/uipath/_cli/_dev/_terminal/_utils/_chat.py
This PR fixes chat aggregations in the terminal UI by improving how conversation events are processed and displayed. The changes focus on better handling of content parts, tool calls, and updating the visual presentation.
=> fix: chat aggregations

pyproject.toml, src/uipath/models/action_schema.py, src/uipath/models/actions.py, src/uipath/models/assets.py, src/uipath/models/attachment.py, src/uipath/models/connections.py, src/uipath/models/context_grounding.py, src/uipath/models/context_grounding_index.py, src/uipath/models/job.py, src/uipath/models/processes.py, src/uipath/models/queues.py
Fix: https://github.com/UiPath/uipath-python/issues/530
https://docs.pydantic.dev/latest/concepts/serialization/#custom-serializers
=> fix(json_encoder): adapt json serialization to pydantic v2

pyproject.toml, src/uipath/tracing/_traced.py, src/uipath/tracing/_utils.py, tests/tracing/test_traced.py, uv.lock
Sometimes `@traced()` inputs are not properly serialized
```toml
[project]
"uipath==2.1.58.dev1006071226",
"uipath>=2.1.58.dev1006070000,<2.1.58.dev1006080000"
]
```
=> fix(trace): fix traced serialization

pyproject.toml, src/uipath/_cli/_evals/_evaluator_factory.py, src/uipath/_cli/_evals/_models/_trajectory_span.py, src/uipath/_cli/_evals/_runtime.py, src/uipath/eval/evaluators/trajectory_evaluator.py, src/uipath/eval/models/models.py
Add trajectory evaluator.
```toml
[project]
"uipath==2.1.67.dev1006161282",
"uipath>=2.1.67.dev1006160000,<2.1.67.dev1006170000"
]
```
=> feat: trajectory eval

.github/labeler.yml, .github/workflows/auto-label.yml, .github/workflows/test-uipath-langchain.yml, .github/workflows/test-uipath-llamaindex.yml
- Adding the `test:uipath-langchain` label to a PR will run the unit tests and integration tests from the `uipath-langchain-python` repository using the changes from the current branch.
- Same with the `test:uipath-llamaindex` label.
=> tests: add workflows to test langchain and llamaindex repositories

src/uipath/_cli/_auth/_auth_service.py, src/uipath/_cli/_auth/_models.py, src/uipath/_cli/_auth/_oidc_utils.py, src/uipath/_cli/_auth/_portal_service.py, src/uipath/_cli/_auth/_url_utils.py, src/uipath/_cli/_auth/_utils.py, src/uipath/_cli/_utils/_common.py, src/uipath/_cli/cli_auth.py, src/uipath/_services/external_application_service.py, src/uipath/_utils/_auth.py, src/uipath/models/auth.py, tests/cli/test_auth.py, tests/cli/test_portal_service_ensure_valid_token.py, tests/cli/test_portal_service_refresh_token.py, tests/sdk/services/test_external_application_service.py
```toml
[project]
"uipath==2.1.68.dev1006081455",
"uipath>=2.1.68.dev1006080000,<2.1.68.dev1006090000"
]
```
=> refactor: cli auth

pyproject.toml, samples/calculator/evals/eval-sets/default.json, samples/calculator/evals/evaluators/llm-as-a-judge.json, src/uipath/_cli/_evals/_console_progress_reporter.py, src/uipath/_cli/_evals/_models/_output.py, src/uipath/_cli/_evals/_progress_reporter.py, src/uipath/_cli/_evals/_runtime.py, src/uipath/_cli/_runtime/_contracts.py, src/uipath/_cli/_runtime/_logging.py, src/uipath/_cli/cli_eval.py, src/uipath/_cli/middlewares.py, src/uipath/_events/_events.py
https://github.com/UiPath/uipath-python/issues/627
Enhances the uipath eval command with a console progress reporter. Introduces clean separation between user-friendly display and debug output modes.
uipath eval main.py evals/eval-sets/evaluation-set-default.json
Working in Orchestrator:
- Included execution logs per each evaluation
```toml
[project]
"uipath==2.1.75.dev1006381538",
"uipath>=2.1.75.dev1006380000,<2.1.75.dev1006390000"
]
```
=> feat: format uipath eval output to show scores
